version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2182"
  kafka:
    image: wurstmeister/kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.217
      KAFKA_CREATE_TOPIC: "door-state"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
    links:
      - zookeeper
  websocket-server:
    build: .
    ports:
      - "30005:30005"
    environment:
      WS_HOST: 0.0.0.0
      WS_PORT: 30005
      KAFKA_HOST: kafka
      KAFKA_HOST_PORT: 9092
      KAFKA_TOPIC: "door-state"
      KAFKA_GROUP_ID: "consumer-1"
    restart: on-failure
    depends_on:
      - kafka
